
package pingui;

import javax.swing.JOptionPane;


public class Romprc extends javax.swing.JFrame {
 int cont=0;

    public Romprc() {
        initComponents();
         this.setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        c = new javax.swing.JLabel();
        p2 = new javax.swing.JLabel();
        bufanda = new javax.swing.JLabel();
        carita = new javax.swing.JLabel();
        bi6 = new javax.swing.JLabel();
        bd = new javax.swing.JLabel();
        brazoder = new javax.swing.JLabel();
        brazoiz = new javax.swing.JLabel();
        pder = new javax.swing.JLabel();
        pataarriba = new javax.swing.JLabel();
        p1 = new javax.swing.JLabel();
        panci = new javax.swing.JLabel();
        bi4 = new javax.swing.JLabel();
        pataabajo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        c.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pingui/cara.PNG"))); // NOI18N
        c.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                cMouseDragged(evt);
            }
        });
        c.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                cMouseReleased(evt);
            }
        });
        getContentPane().add(c, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 270, 170, -1));

        p2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pingui/buf.PNG"))); // NOI18N
        p2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                p2MouseDragged(evt);
            }
        });
        p2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                p2MouseReleased(evt);
            }
        });
        getContentPane().add(p2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 310, -1, 120));

        bufanda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pingui/buf2.PNG"))); // NOI18N
        bufanda.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                bufandaMouseDragged(evt);
            }
        });
        getContentPane().add(bufanda, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 370, -1, 120));

        carita.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pingui/cara1.PNG"))); // NOI18N
        getContentPane().add(carita, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 260, 170, 150));

        bi6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pingui/bi.PNG"))); // NOI18N
        bi6.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                bi6MouseDragged(evt);
            }
        });
        bi6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                bi6MouseReleased(evt);
            }
        });
        getContentPane().add(bi6, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 350, -1, 60));

        bd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pingui/bd.PNG"))); // NOI18N
        bd.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                bdMouseDragged(evt);
            }
        });
        bd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                bdMouseReleased(evt);
            }
        });
        getContentPane().add(bd, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 190, -1, 120));

        brazoder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pingui/sd.PNG"))); // NOI18N
        brazoder.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                brazoderMouseDragged(evt);
            }
        });
        getContentPane().add(brazoder, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 360, 100, 110));

        brazoiz.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pingui/bi1.PNG"))); // NOI18N
        brazoiz.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                brazoizMouseDragged(evt);
            }
        });
        getContentPane().add(brazoiz, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 370, 80, 100));

        pder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pingui/pata.PNG"))); // NOI18N
        pder.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                pderMouseDragged(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                pderMouseMoved(evt);
            }
        });
        pder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                pderMouseReleased(evt);
            }
        });
        getContentPane().add(pder, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 200, -1, 60));

        pataarriba.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pingui/patita.PNG"))); // NOI18N
        pataarriba.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                pataarribaMouseDragged(evt);
            }
        });
        getContentPane().add(pataarriba, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 500, 60, 60));

        p1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pingui/panza.PNG"))); // NOI18N
        p1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                p1MouseDragged(evt);
            }
        });
        p1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                p1MouseReleased(evt);
            }
        });
        getContentPane().add(p1, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 220, -1, 120));

        panci.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pingui/panza1.PNG"))); // NOI18N
        getContentPane().add(panci, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 400, -1, 120));

        bi4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pingui/patb.PNG"))); // NOI18N
        bi4.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                bi4MouseDragged(evt);
            }
        });
        bi4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                bi4MouseReleased(evt);
            }
        });
        getContentPane().add(bi4, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 360, -1, 120));

        pataabajo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pingui/pati.PNG"))); // NOI18N
        pataabajo.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                pataabajoMouseDragged(evt);
            }
        });
        getContentPane().add(pataabajo, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 460, -1, 120));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pingui/nubecita.PNG"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 0, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pingui/casitadepingui1.PNG"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 430, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pingui/tablero1.PNG"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 130, 550, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pingui/azul.jpg"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -20, 2660, 380));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pingui/blanco.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-270, 350, 1830, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cMouseDragged
        // TODO add your handling code here:
         c.setLocation(c.getLocation().x +evt.getX() -c.getWidth()/2,c.getLocation().y+evt.getY()-c.getHeight());
    }//GEN-LAST:event_cMouseDragged

    private void bufandaMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bufandaMouseDragged
         
    }//GEN-LAST:event_bufandaMouseDragged

    private void bdMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bdMouseDragged
        // TODO add your handling code here:
       bd.setLocation(bd.getLocation().x +evt.getX() -bd.getWidth()/2,bd.getLocation().y+evt.getY()-bd.getHeight());
    
    }//GEN-LAST:event_bdMouseDragged

    private void brazoderMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_brazoderMouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_brazoderMouseDragged

    private void brazoizMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_brazoizMouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_brazoizMouseDragged

    private void p1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p1MouseDragged
        // TODO add your handling code here:
         p1.setLocation(p1.getLocation().x +evt.getX() -p1.getWidth()/2,p1.getLocation().y+evt.getY()-p1.getHeight());
    
    }//GEN-LAST:event_p1MouseDragged

    private void p2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p2MouseDragged
        // TODO add your handling code here:
          p2.setLocation(p2.getLocation().x +evt.getX() -p2.getWidth()/2,p2.getLocation().y+evt.getY()-p2.getHeight());
    
    }//GEN-LAST:event_p2MouseDragged

    private void bi4MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bi4MouseDragged
        // TODO add your handling code here:
      bi4.setLocation(bi4.getLocation().x +evt.getX() -bi4.getWidth()/2,bi4.getLocation().y+evt.getY()-bi4.getHeight());
    
    }//GEN-LAST:event_bi4MouseDragged

    private void pataarribaMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pataarribaMouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_pataarribaMouseDragged

    private void bi6MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bi6MouseDragged
        // TODO add your handling code here:
         bi6.setLocation(bi6.getLocation().x +evt.getX() -bi6.getWidth()/2,bi6.getLocation().y+evt.getY()-bi6.getHeight());
    
    }//GEN-LAST:event_bi6MouseDragged

    private void pderMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pderMouseDragged
        // TODO add your handling code here:
        pder.setLocation(pder.getLocation().x +evt.getX() -pder.getWidth()/2,pder.getLocation().y+evt.getY()-pder.getHeight());
    
    }//GEN-LAST:event_pderMouseDragged

    private void pataabajoMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pataabajoMouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_pataabajoMouseDragged

    private void pderMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pderMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_pderMouseMoved

    private void cMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cMouseReleased
       
        if ((c.getX()>=459  && c.getX()<=459+170)
           &&(c.getY()>=258 && c.getY()<=258+c.HEIGHT)  || (c.getX()>=460  && c.getX()<=460+170)
           &&(c.getY()>=256 && c.getY()<=256+c.HEIGHT)  || (c.getX()>=458  && c.getX()<=458+170)
           &&(c.getY()>=257 && c.getY()<=257+c.HEIGHT)   )
       {
        cont++;
          if(cont == 7){
             JOptionPane.showMessageDialog(null,"Felicidades ha completado a Pingui");
          }
      }else{
           c.setLocation(750, 270);
           JOptionPane.showMessageDialog(null,  "posicion incorrecta");
       }
//        
        //  JOptionPane.showMessageDialog(null,c.getX()+ " " +c.getY());
       
    }//GEN-LAST:event_cMouseReleased

    private void p2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p2MouseReleased
        // TODO add your handling code here:
        
          if ((p2.getX()>=460 && p2.getX()<=460+p2.WIDTH)
           &&(p2.getY()>=374 && p2.getY()<=374+120)            || (p2.getX()>=460 && p2.getX()<=460+p2.WIDTH)
           &&(p2.getY()>=372 && p2.getY()<=372+120) || (p2.getX()>=457 && p2.getX()<=457+p2.WIDTH)
           &&(p2.getY()>=371 && p2.getY()<=371+120)  ||
                  (p2.getX()>=459 && p2.getX()<=459+p2.WIDTH)
           &&(p2.getY()>=374 && p2.getY()<=374+120)  
                  ||
                  (p2.getX()>=459 && p2.getX()<=459+p2.WIDTH)
           &&(p2.getY()>=372 && p2.getY()<=372+120)     ||
                  (p2.getX()>=458 && p2.getX()<=458+p2.WIDTH)
           &&(p2.getY()>=370 && p2.getY()<=370+120)   ||
                  (p2.getX()>=459 && p2.getX()<=459+p2.WIDTH)
           &&(p2.getY()>=373 && p2.getY()<=373+120) )
       {
        cont++;
          if(cont == 7){
             JOptionPane.showMessageDialog(null,"Felicidades ha  completado a pingui");
          }
      }else{
           p2.setLocation(1050, 310);
           JOptionPane.showMessageDialog(null,"posicion incorrecta");
       }
//        
       //   JOptionPane.showMessageDialog(null,p2.getX()+ " " +p2.getY());
    }//GEN-LAST:event_p2MouseReleased

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void pderMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pderMouseReleased
     
            if ((pder.getX()>=525  && pder.getX()<=525+ pder.WIDTH)
           &&(pder.getY()>=497 && pder.getY()<=497+60)  || 
               (pder.getX()>=526  && pder.getX()<=526+ pder.WIDTH)
           &&(pder.getY()>=500 && pder.getY()<=500+60)  || 
               (pder.getX()>=526  && pder.getX()<=526+ pder.WIDTH)
           &&(pder.getY()>=498 && pder.getY()<=498+60)  || 
               (pder.getX()>=527  && pder.getX()<=527+ pder.WIDTH)
           &&(pder.getY()>=496 && pder.getY()<=496+60) ||(pder.getX()>=525  && pder.getX()<=525+ pder.WIDTH)
           &&(pder.getY()>=498 && pder.getY()<=498+60)     )
       {
        cont++;
          if(cont == 7){
             JOptionPane.showMessageDialog(null,"Felicidades ha completado a Pingui");
          }
      }else{
           pder.setLocation(780, 200);
           JOptionPane.showMessageDialog(null,  "posicion incorrecta");
       }
        
       //   JOptionPane.showMessageDialog(null,pder.getX()+ " " +pder.getY());
        
        
        
        
        
    }//GEN-LAST:event_pderMouseReleased

    private void p1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_p1MouseReleased
        // TODO add your handling code here:
        
          if ((p1.getX()>=461  && p1.getX()<=461+ p1.WIDTH)
           &&(p1.getY()>=397 && p1.getY()<=397+120)  )
       {
        cont++;
          if(cont == 7){
             JOptionPane.showMessageDialog(null,"Felicidades ha completado a Pingui");
          }
      }else{
           p1.setLocation(910, 220);
           JOptionPane.showMessageDialog(null,  "posicion incorrecta");
       }
//        
        
        
      //   JOptionPane.showMessageDialog(null,p1.getX()+ " " +p1.getY());
        
        
    }//GEN-LAST:event_p1MouseReleased

    private void bi4MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bi4MouseReleased
        // TODO add your handling code here:
        
          if ((bi4.getX()>=459  && bi4.getX()<=459+bi4.WIDTH)
           &&(bi4.getY()>=458 && bi4.getY()<=458+120) || (bi4.getX()>=461  && bi4.getX()<=461+bi4.WIDTH)
           &&(bi4.getY()>=457 && bi4.getY()<=457+120) 
                 )
       {
        cont++;
          if(cont == 7){
             JOptionPane.showMessageDialog(null,"Felicidades ha completado a Pingui");
          }
      }else{
           bi4.setLocation(980, 360);
           JOptionPane.showMessageDialog(null,  "posicion incorrecta");
       }
       
       //   JOptionPane.showMessageDialog(null,bi4.getX()+ " " +bi4.getY());
        
        
        
    }//GEN-LAST:event_bi4MouseReleased

    private void bi6MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bi6MouseReleased
        // TODO add your handling code here:
        
        if ((bi6.getX()>=421  && bi6.getX()<=421+bi6.WIDTH)
           &&(bi6.getY()>=386 && bi6.getY()<=386+60)  || (bi6.getX()>=421  && bi6.getX()<=421+bi6.WIDTH)
           &&(bi6.getY()>=385 && bi6.getY()<=385+60)  || (bi6.getX()>=420  && bi6.getX()<=420+bi6.WIDTH)
           &&(bi6.getY()>=385 && bi6.getY()<=385+60)) 
                 
       {
        cont++;
          if(cont == 7){
             JOptionPane.showMessageDialog(null,"Felicidades ha completado a Pingui");
          }
      }else{
           bi6.setLocation(920, 350);
           JOptionPane.showMessageDialog(null,  "posicion incorrecta");
       }
       
          //JOptionPane.showMessageDialog(null,bi6.getX()+ " " +bi6.getY());
        
        
    }//GEN-LAST:event_bi6MouseReleased

    private void bdMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bdMouseReleased
         
           
        if ((bd.getX()>=557  && bd.getX()<=557+bd.WIDTH)
           &&(bd.getY()>=345 && bd.getY()<=345+120) || (bd.getX()>=572  && bd.getX()<=572+bd.WIDTH)
           &&(bd.getY()>=344 && bd.getY()<=344+120)  || (bd.getX()>=572  && bd.getX()<=572+bd.WIDTH)
           &&(bd.getY()>=345 && bd.getY()<=345+120)  ) 
                 
       {
        cont++;
          if(cont == 7){
             JOptionPane.showMessageDialog(null,"Felicidades ha completado a Pingui");
          }
      }else{
           bd.setLocation(1100, 190);
           JOptionPane.showMessageDialog(null,  "posicion incorrecta");
       }
       
        //  JOptionPane.showMessageDialog(null,bd.getX()+ " " +bd.getY());
        
        
        
    }//GEN-LAST:event_bdMouseReleased
    
    public static void main(String args[]) {
      
        
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Romprc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bd;
    private javax.swing.JLabel bi4;
    private javax.swing.JLabel bi6;
    private javax.swing.JLabel brazoder;
    private javax.swing.JLabel brazoiz;
    private javax.swing.JLabel bufanda;
    private javax.swing.JLabel c;
    private javax.swing.JLabel carita;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel p1;
    private javax.swing.JLabel p2;
    private javax.swing.JLabel panci;
    private javax.swing.JLabel pataabajo;
    private javax.swing.JLabel pataarriba;
    private javax.swing.JLabel pder;
    // End of variables declaration//GEN-END:variables
}
